title: "Domain | Play Store tutorials and tops of apps"
email: contact@domain.com
timezone: UTC
baseurl: "gplaysite/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Adrian
paginate: 10
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 3
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  adrian:
    name: Adrian
    display_name: Adrian
    avatar: 'assets/images/adrian.png'
    email: contact@domain.com
    web: https://domain.com/
    description: "Author of Domain.com, he’s very enthusiastic about the Android platform, staying tuned to everything new about it. He's a master of Google Play Store, knowing the right apps to use depending on the needs of use."

# Social
social:
  instagram: https://www.instagram.com/
  facebook: https://www.facebook.com/
  twitter: https://twitter.com/

  #Ads
sidebar_ad: false
header_ad: false
index_intro: true
newsletter_section: true

#language







# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives